version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: archimedes-mq
    restart: unless-stopped
    ports:
      - "1883:1883"  # MQTT Port
      - "9001:9001"  # WebSocket (optional)
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log

